package Telas;

import Classes.Receptor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joaol
 */
public class TelaCadastroMedico extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroMedico
     */
    public TelaCadastroMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoNomeCadastroMedico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoCPFCadastroMedico = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        caixaSexoCadastroMedico = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        caixaSangueCadastroMedico = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        botaoOKCadastroMedico = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        campoCelularCadastroMedico = new javax.swing.JFormattedTextField();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 60, 60, 20);
        getContentPane().add(campoNomeCadastroMedico);
        campoNomeCadastroMedico.setBounds(120, 51, 198, 26);

        jLabel2.setText("CPF:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 90, 70, 16);

        try {
            campoCPFCadastroMedico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(campoCPFCadastroMedico);
        campoCPFCadastroMedico.setBounds(119, 83, 199, 26);

        jLabel3.setText("Sexo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 130, 70, 16);

        caixaSexoCadastroMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "   ", "Homem", "Mulher" }));
        getContentPane().add(caixaSexoCadastroMedico);
        caixaSexoCadastroMedico.setBounds(119, 121, 81, 26);

        jLabel4.setText("Tipo Sanguineo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(15, 164, 100, 16);

        caixaSangueCadastroMedico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "     ", "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));
        getContentPane().add(caixaSangueCadastroMedico);
        caixaSangueCadastroMedico.setBounds(113, 159, 76, 26);

        jLabel5.setText("Celular:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(62, 208, 39, 16);

        jLabel6.setText("Motivo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(61, 241, 40, 16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(113, 241, 238, 90);

        botaoOKCadastroMedico.setText("Cadastrar");
        botaoOKCadastroMedico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoOKCadastroMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOKCadastroMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(botaoOKCadastroMedico);
        botaoOKCadastroMedico.setBounds(267, 366, 84, 27);

        jButton1.setText("Voltar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(15, 18, 76, 27);

        try {
            campoCelularCadastroMedico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(campoCelularCadastroMedico);
        campoCelularCadastroMedico.setBounds(113, 203, 130, 26);

        setSize(new java.awt.Dimension(394, 484));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoOKCadastroMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOKCadastroMedicoActionPerformed
        Receptor ReceptorTela=new Receptor();

String Nome=(campoNomeCadastroMedico.getText());
String CPF=(campoCPFCadastroMedico.getText());
String Tiposanguinho=(String) (caixaSangueCadastroMedico.getSelectedItem());
String Sexo=(String) (caixaSexoCadastroMedico.getSelectedItem());
String Celular=(campoCelularCadastroMedico.getText());
String Motivo=(jTextArea1.getText());

ReceptorTela.setNome(Nome);
ReceptorTela.setCPF(CPF);
ReceptorTela.setTiposanguineo(Tiposanguinho);
ReceptorTela.setSexo(Sexo);
ReceptorTela.setCelular(Celular);
ReceptorTela.setMotivo(Motivo);
        try {
            ReceptorTela.inserir();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
       TelaPrincipalMDI T1 = new TelaPrincipalMDI();
        T1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoOKCadastroMedicoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaPrincipalMDI T1= new TelaPrincipalMDI();
        T1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoOKCadastroMedico;
    private javax.swing.JComboBox<String> caixaSangueCadastroMedico;
    private javax.swing.JComboBox<String> caixaSexoCadastroMedico;
    private javax.swing.JFormattedTextField campoCPFCadastroMedico;
    private javax.swing.JFormattedTextField campoCelularCadastroMedico;
    private javax.swing.JTextField campoNomeCadastroMedico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
